modules/urls.py
from django.urls import path
from . import views
from .views import module_detail, my_module


app_name = 'modules'
urlpatterns = [
    path('', views.course_list, name='home'),
    path('modules/', views.module_list, name='module_list'),
    path('module_detail/', module_detail, name='module_detail'),
    path('unregister_module/<str:module_code>/', views.unregister_module, name='unregister_module'),
    path('register_module/<str:module_code>/', views.register_module, name='register_module'),
    path('my_module/', my_module, name='my_module'),
    path('learning_list/', views.learning_list, name='learning_list'),
    path('contact', views.contact, name = 'contact'),
    path('search_course/', views.search_course, name='search_course'),

]

myCourseApp/urls.py
from django.contrib import admin
from django.urls import path, include
from modules import views
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from modules.views import course_list, generate_report, book_api


urlpatterns = [
    path('', course_list, name = 'home'),
    path('admin/', admin.site.urls),
    path('about', views.about, name = 'about'),
    path('register', user_views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'logout.html'), name='logout'),
    path('profile', user_views.profile, name = 'profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),
    path('courses/', include('modules.urls')),
    path('password-reset/', user_views.password_reset_view, name='password_reset'),
    path('generate-report/', generate_report, name='generate_report'),
    path('book_api/', book_api, name='book_api'),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .views import password_reset_view, edit_profile


app_name = 'users'
urlpatterns = [
    path('password-reset/', password_reset_view, name='password_reset'),
    path('profile/edit/', edit_profile, name='edit_profile')
]

modules/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.utils import timezone

class Course(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE)
    code = models.CharField(max_length=255, blank=True)
    image = models.ImageField(default='course_pics/logo.jpg', upload_to='course_pics')
    description = models.TextField(blank=True, null=True)
    duration = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.group.name

class Module(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20, unique=True)
    credit = models.CharField(max_length=10)
    category = models.CharField(max_length=250, choices=(
        ("Compulsory", "Compulsory"),
        ("Elective", "Elective"),
    ))
    description = models.TextField()
    available = models.BooleanField()
    courses = models.ManyToManyField(Course)
    def __str__(self):
        return self.name
    
class RegisteredUser(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    module_code = models.ForeignKey(Module, on_delete=models.CASCADE) 
    registration_date = models.DateTimeField(default=timezone.now, editable=False)
    
    def __str__(self):
        return f"{self.student} - {self.module_code}"
    
class Learning(models.Model):
    title = models.CharField(max_length=100)
    files = models.FileField(upload_to='learning_files', blank=True)
    description = models.TextField()
    module = models.ForeignKey(Module, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} - {self.module}"

modules/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

modules/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Course, Module, RegisteredUser, Learning
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ContactForm
from django.core.mail import send_mail
from django.core.paginator import Paginator
import requests

def about(request):
    return render(request, 'about.html')

def course_list(request):
    try:
        # Get all courses
        courses = Course.objects.all()
        
        # Paginate the courses
        items_per_page = 6
        paginator = Paginator(courses, items_per_page)
        
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        # Pass the paginated courses to the template
        return render(request, 'home.html', {'page_obj': page_obj})
    
    except Course.DoesNotExist:
        # Handle error case if no courses are found
        return render(request, 'error.html', {'message': 'No courses found'})

def module_list(request):
    course_name = request.GET.get('course_name')

    try:
        # Filter the modules based on the provided course_name
        filtered_modules = Module.objects.filter(courses__group__name=course_name)

        # Create a list to store module information
        module_info = []

        # Iterate over the filtered modules and extract the relevant information
        for module in filtered_modules:
            course_name = module.name
            course_code = module.code
            credit = module.credit
            category = module.category
            available = module.available
            description = module.description
            #course_title = module.name.name.all()

            # Create a dictionary with the module information
            module_data = {
                'course_name': course_name,
                'course_code': course_code,
                'credit': credit,
                'category': category,
                'available': available,
                'description': description,
                #'course_title': course_title
            }

            # Append the module data to the list
            module_info.append(module_data)

        # Pass the module information to the template
        return render(request, 'module_list.html', {'modules': module_info})
    except Module.DoesNotExist:
        # Handle error case if no modules are found
        return render(request, 'error.html', {'message': 'No modules found'})
    
@login_required
def module_detail(request):
    course_code = request.GET.get('course_code')

    try:
        # Filter the modules based on the provided course_code
        filtered_modules = Module.objects.filter(code=course_code)

        # Create a list to store module information
        module_info = []

        # Iterate over the filtered modules and extract the relevant information
        for module in filtered_modules:
            course_name = module.name
            course_code = module.code
            credit = module.credit
            category = module.category
            available = module.available
            description = module.description

            # Create a dictionary with the module information
            module_data = {
                'course_name': course_name,
                'course_code': course_code,
                'credit': credit,
                'category': category,
                'available': available,
                'description': description,
            }

            # Append the module data to the list
            module_info.append(module_data)

        # Filter the registered users based on the provided course_code
        registered_users = RegisteredUser.objects.filter(module_code__code=course_code)

        # Create a list to store user information
        user_info = []

        # Iterate over the filtered users and extract the relevant information
        for registered_user in registered_users:
            student = registered_user.student
            registration_date = registered_user.registration_date

            # Create a dictionary with the user information
            user_data = {
                'student': student,
                'registration_date': registration_date,
            }

            # Append the user data to the list
            user_info.append(user_data)

        # Check if the user is a registered student for the module
        is_registered = RegisteredUser.objects.filter(student=request.user, module_code__code=course_code).exists()

        # Pass the module and user information to the template
        context = {
            'modules': module_info,
            'users': user_info,
            'is_registered': is_registered,
        }
        return render(request, 'module_detail.html', context)

    except Module.DoesNotExist:
        # Handle error case if no modules are found
        return render(request, 'error.html', {'message': 'No modules found'})
    except RegisteredUser.DoesNotExist:
        # Handle error case if no users are found
        return render(request, 'error.html', {'message': 'No users found'})


@login_required
def register_module(request, module_code):
    # Get the user and module based on the current user and module code
    user = request.user
    course_name = request.GET.get('course_name')
    try:
        # Get the module based on the module_code and course_name
        module = get_object_or_404(Module, code=module_code)
        course = get_object_or_404(Course, group__name=course_name)
        
        # Create a new Module object and save it to the database
        course_module = Module(name=course, code=module)
        
        
        # Create a new RegisteredUser object and save it to the database
        registered_user = RegisteredUser(student=user, module_code=course_module.code)
        registered_user.save()
        
        # Redirect to the module detail page or any other desired page
        messages.success(request, f'You have registered for this module successfully')
        # Redirect back to the same page
        return redirect(request.META['HTTP_REFERER'])

    except (Module.DoesNotExist, Course.DoesNotExist):
        # Handle the case when the module or course does not exist
        return render(request, 'module_not_found.html')
    
@login_required
def unregister_module(request, module_code):
    # Get the user and module based on the current user and module code
    user = request.user
    course_code = request.GET.get('course_code')
    try:
        # Get the registered user for the module
        registered_user = RegisteredUser.objects.get(student=user, module_code__code=course_code)
        
        # Delete the registered user
        registered_user.delete()
        messages.warning(request, f'You have un-registered from this module')
        return redirect(request.META['HTTP_REFERER'])

    except (Module.DoesNotExist, RegisteredUser.DoesNotExist):
        # Handle the case when the module or registered user does not exist
        return render(request, 'module_not_found.html')

def my_module(request):
    student_name = request.user  # Replace with the actual student name

    # Query the RegisteredUser model to filter by student name
    registered_users = RegisteredUser.objects.filter(student__username=student_name)

    # Query the Module model to retrieve the corresponding module information
    modules = Module.objects.filter(pk__in=registered_users.values_list('module_code', flat=True))

    return render(request, 'myModule.html', {'modules': modules})

def learning_list(request):
    course_code = request.GET.get('course_code')

    try:
        # Filter the learnings based on the provided course_code
        filtered_learnings = Learning.objects.filter(module__code=course_code)

        # Create a list to store learning information
        learning_info = []

        # Iterate over the filtered learnings and extract the relevant information
        for learning in filtered_learnings:
            title = learning.title
            files = learning.files
            description = learning.description

            # Create a dictionary with the learning information
            learning_data = {
                'title': title,
                'files': files,
                'description': description,
            }

            # Append the learning data to the list
            learning_info.append(learning_data)

        # Pass the learning information to the template
        return render(request, 'learning_list.html', {'learnings': learning_info})
    except Learning.DoesNotExist:
        # Handle error case if no learnings are found
        return render(request, 'error.html', {'message': 'No learning material found'})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            # Compose the email message
            email_subject = f"Contact Form Submission - {subject}"
            email_body = f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}"

            # Send the email using Django's send_mail function
            send_mail(
                email_subject,
                email_body,
                'sample@gmail.com',  # Replace this with your own email address
                ['sample@gmail.com'],  # Add your Gmail account here
                fail_silently=False,
            )

            messages.success(request, 'Thank you for contacting us. We will get back to you shortly.')
            return redirect('./')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})

def search_course(request):
    query = request.GET.get('q')

modules/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png"  href="{% static 'img/favicon.png' %}">
  <title>
   Module Registration System - {{ title }}
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}?v=3.1.0" rel="stylesheet" />

  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>


<body class="g-sidenav-show  bg-gray-200">
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" {% url 'modules:home' %} " target="#">
        <img src="{% static 'img/shu.png' %}" alt="Moodle Registration System" class="ms-1 font-weight-bold"><span class="ms-1 font-weight-bold text-white"> SHU Registration App</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
       <li class="nav-item">
    <a class="nav-link {% if request.resolver_match.url_name == 'home' %}text-white active bg-gradient-primary{% else %}text-white{% endif %}" href="{% url 'modules:home' %}">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">dashboard</i>
        </div>
        <span class="nav-link-text ms-1">Home</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link {% if request.resolver_match.url_name == 'my_module' %}text-white active bg-gradient-primary{% else %}text-white{% endif %}" href="{% url 'modules:my_module' %}">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1">My Modules</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link {% if request.resolver_match.url_name == 'about' %}text-white active bg-gradient-primary{% else %}text-white{% endif %}" href="{% url 'about' %}">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1">About Us</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}text-white active bg-gradient-primary{% else %}text-white{% endif %}" href="{% url 'modules:contact' %}">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10"></i>
        </div>
        <span class="nav-link-text ms-1">Contact Us</span>
    </a>
</li>

<li class="nav-item">
    {% if user.is_authenticated %}
    <a class="nav-link text-white {% if request.resolver_match.url_name == 'profile' %}active bg-gradient-primary{% endif %}" href="{% url 'profile' %}">
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">login</i>
        </div>
        <span class="nav-link-text ms-1">Profile</span>
    </a>
    {% else %}
    <!-- Render appropriate content for unauthenticated users -->
    {% endif %}
</li>
<li class="nav-item">
  <a class="nav-link {% if request.resolver_match.url_name == 'book_api' %}text-white active bg-gradient-primary{% else %}text-white{% endif %}" href="{% url 'book_api' %}">
    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
      <i class="material-icons opacity-10">receipt_long</i>
    </div>
    <span class="nav-link-text ms-1">E-Library</span>
  </a>
</li>
        <li class="nav-item">
          {%if user.is_authenticated%}
          <a class="nav-link text-white "href="{% url 'logout' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Logout</span>
          </a>
          {%else %}
          {%endif%}
        </li>

        <li class="nav-item">
          {% if user.is_authenticated %}
          {% if request.user.is_staff %}
          <a class="nav-link text-white " href="\admin">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Admin</span>
          </a>
          {% else %}
          {% endif %}{% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          {% if request.user.is_staff %}
          <a id="generate-report-link" class="nav-link text-white " href="{% url 'generate_report' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Generate Report</span>
          </a>
          {% else %}
          {% endif %}{% endif %}
        </li> 
      </ul>

    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <div class="mx-3">
          </div>
    </div>
  </aside>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Home</li>
          </ol>
          
        </nav>
      
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
  <div class="ms-md-auto pe-md-3 d-flex align-items-center">
    <div class="input-group input-group-outline">
      <form method="get" action="{% url 'modules:search_course' %}">
      <label for="inputField" class="form-label" id="labelField">Search for Course</label>
      <input type="text" id="inputField" class="form-control"  oninput="handleInput()" name="q" value="{{ query }}">

      </form>
    </div>
    
    <script>
      const inputField = document.getElementById('inputField');
      const labelField = document.getElementById('labelField');
  
      function handleInput() {
          if (inputField.value.trim() !== '') { // Check for non-empty and non-whitespace input
              labelField.style.visibility = 'hidden';
          } else {
              labelField.style.visibility = 'visible';
          }
      }
  
      // Attach the input event listener
      inputField.addEventListener('input', handleInput);
  
      // Call the function initially to ensure correct initial display
      handleInput();
  </script>
  </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              </li>
            <li class="mt-2">
             </li>
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
          
            
            {% if user.is_authenticated %}
            <li class="nav-item d-flex align-items-center">
              <span class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Logged in as {{ user.username }}</span>
              </span>
            </li>
          {% else %}
            <li class="nav-item d-flex align-items-center">
              <a href="{% url 'login' %}" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign In</span>
              </a>
            </li>
          {% endif %}
          
            </li>
            {% if user.is_authenticated%}
            
              {%else%}
              <a href="{% url 'register' %}" class="nav-link text-body font-weight-bold px-0">
                &nbsp;&nbsp; <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Register</span>
              </a>
            </li>
            {%endif%}
          </ul>
        </div>
      </div>
    </nav>
    
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        {% if messages %}

{% for message in messages %}

<div class="alert alert-{{message.tags}}">{{ message }}</div>

{% endfor %}

{% endif %}
        <h4 class="mb-0">{% block content %}{% endblock %}</h4>
      </div>
      
      
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              
            </div>
            <div class="col-lg-6">
             
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  
  </div>
  <!--   Core JS Files   -->
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>

</body>

</html>

modules/templates/contact.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://c2063081.blob.core.windows.net/static/css/custom-form.css">
<h4>SHU Course Moodle Services - Contact Us</h4>
<form method="post" class="custom-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

modules/templates/module_detail.html
{% extends "base.html" %}

{% block content %}
<style>
  .course-module {
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 10px;
    margin-bottom: 10px;
    background-color: #f5f5f5;
  }
  
  .course-module h3 {
    font-size: 18px;
    font-weight: bold;
    margin-top: 0;
    margin-bottom: 5px;
  }
  
  .course-module p {
    font-size: 14px;
    margin: 0;
  }
  
  .course-module .description {
    font-style: italic;
  }
  
  .course-module .courses {
    font-weight: bold;
    margin-top: 10px;
  }
  
  .course-module .course-list {
    margin: 0;
    padding: 0;
    list-style-type: none;
  }
  
  .course-module .course-list li {
    font-size: 14px;
    margin-bottom: 5px;
  }
  
  .course-module .course-list li:before {
    content: "\2022";
    color: #555;
    display: inline-block;
    width: 1em;
    margin-left: -1em;
  }
  </style>
<h4>Browse Modules - {{ request.GET.course_code }}</h4>
{% for module in modules %}
  {% ifchanged module.course_code %}
    <div class="course-module">
      <a href="#"><h3>Course Name: {{ module.course_name }} - {{ module.course_code }}</h3></a>
      <p>Credit: {{ module.credit }}</p>
      <p>Category: {{ module.category }}</p>
      <p>Available: {{ module.available }}</p>
      <p>Description: {{ module.description }}</p>
      <br>
      
      {% if is_registered %}
      <p>You are registered for this module.</p>
      <a href="{% url 'modules:unregister_module' module.course_code %}?course_code={{ request.GET.course_code }}&course_name={{ request.GET.course_name }}" class="unregister-button" style="color: red;">Unregister</a>
      {% else %}
      <p>You are not registered for this module.</p>
        <a href="{% url 'modules:register_module' module.course_code %}?course_code={{ request.GET.course_code }}&course_name={{ request.GET.course_name }}" class="register-button">Register</a><br>
      {% endif %}
     
    </div>
    <div class="course-module">
      <h6>Registered Users</h6>
      <div class="table-responsive">
        <table class="table align-items-center mb-0">
          <thead>
            <tr>
                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Full Name</th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Registered Date</th>
            </tr>
        </thead>
      {% if users %}
        <ul>
          {% for user in users %} 
           <tbody>
  <tr>
    <td>
      <div class="d-flex px-2 py-1">
        <div>
          <img src="{{ user.student.student.image.url }}" class="avatar avatar-sm me-3" alt="xd">
        </div>
        <div class="d-flex flex-column justify-content-center">
          <h6 class="mb-0 text-sm">{{ user.student.first_name }} {{ user.student.last_name }}</h6>
        </div>
      </div>
    </td>
    <td class="align-middle text-center text-sm">
      <span class="text-xs font-weight-bold"> {{ user.registration_date }}</span>
    </td>
  </tr>
</tbody>
{% endfor %}
</ul>
{% else %}
<p>No registered users for this module.</p>
{% endif %}
</div>
{% endifchanged %}

<div class="#">

</table>
</div>
</div>
{% endfor %}
{% endblock %}

modules/templates/myModule.html
{% extends "base.html" %}

{% block content %}
<style>
.course-module {
  border: 1px solid #ccc;
  border-radius: 5px;
  padding: 10px;
  margin-bottom: 10px;
  background-color: #f5f5f5;
}

.course-module h3 {
  font-size: 18px;
  font-weight: bold;
  margin-top: 0;
  margin-bottom: 5px;
}

.course-module p {
  font-size: 14px;
  margin: 0;
}

.course-module .description {
  font-style: italic;
}

.course-module .courses {
  font-weight: bold;
  margin-top: 10px;
}

.course-module .course-list {
  margin: 0;
  padding: 0;
  list-style-type: none;
}

.course-module .course-list li {
  font-size: 14px;
  margin-bottom: 5px;
}

.course-module .course-list li:before {
  content: "\2022";
  color: #555;
  display: inline-block;
  width: 1em;
  margin-left: -1em;
}
</style>

<h4>Browse Modules - My Modules</h4>
{% for module in modules %}
<div class="course-module">
    <h3>Module Name: {{ module.name }}</h3>
        <p>Module Code: {{ module.code }}</p>
        <p>Credit: {{ module.credit }}</p>
        <p>Category: {{ module.category }}</p>
        <p>Description: {{ module.description }}</p>
        <br>
        <a href="{% url 'modules:learning_list' %}?course_code={{ module.code }}"  style="color: Blue;">Browse Learning Materials</a>
      <br>
      <a href="{% url 'modules:unregister_module' module.code %}?course_code={{ module.code }}&course_name={{ request.GET.course_name }}" class="unregister-button" style="color: red;">Unregister</a>
    </div>
    {% empty %}
        <p>No modules found.</p>
    {% endfor %}

 
{% endblock %}

modules/templates/search_course.html
{% extends "base.html" %}
{% block content %}

<h5>Search for Courses - {{ request.GET.q }}</h5><br>
{% for course in courses %}
<div class="col-lg-4 col-md-6 mt-4 mb-4">
    <div class="card z-index-2">
      <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
        <div class="#">
          <div class="chart" style="display: flex; justify-content: center; align-items: center; height: 190px;">
            <img class="chart-canvas" src="{{ course.image.url }}" height="200" width="300" alt="Course Image">
        </div>
        

      </div>
      </div>
      <div class="card-body" style="max-height: 10px; overflow: fixed;">
        <ul class="course-list" style="justify-content: center;">
            <li><a href="{% url 'modules:module_list' %}?course_name={{ course.group.name }}">{{ course.group.name }}</a></li>
        </ul>
    </div>
    </div>
  </div>
{% endfor %}
{% endblock %}